SELECT TABLE_SCHEMA, TABLE_NAME,
            PARTITION_NAME,PARTITION_DESCRIPTION, TABLE_ROWS,
            ROUND(DATA_LENGTH/(1024*1024),2) AS 'DATA_SIZE(MB)',
            ROUND(INDEX_LENGTH/(1024*1024),2) AS 'INDEX_SIZE(MB)'          
FROM INFORMATION_SCHEMA.PARTITIONS
WHERE PARTITION_NAME IS NOT NULL
order by DATA_LENGTH desc
limit 30;  
